<script lang="ts">
  import ConversionTool from '$lib/ConversionTool.svelte';
</script>

<!--
  Generated by scripts/generate-conversion-routes.mjs — do not hand-edit.

  One directional page per format × direction (README §24). The engine operation
  is shared with the opposite direction; only the entry point differs, which is
  why these are distinct pages rather than tabs on one.
-->
<ConversionTool
  title="PDF to PNG image"
  description="Turn PDF pages into PNG image locally, in your browser. Nothing is uploaded."
  format="png"
  direction="from-pdf"
  accept=".png,image/png"
/>
