import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';

/**
 * P7-10's Done-when: "the same recipe JSON produces byte-equivalent output in both environments."
 *
 * `packages/cli/test/parity.test.mjs` covers half of that, and the half it covers is the easy
 * one: it compares the CLI's written file against an in-process Node `run()` — the same function,
 * in the same runtime, in the same process. That proves the filesystem write is not corrupting
 * bytes. It cannot detect a Node-versus-browser divergence, because it never runs the browser
 * half. Two environments that disagreed would pass that test unchanged.
 *
 * This spec closes the gap. It runs the same recipe through the same engine *inside a real page*
 * and compares the hash against the CLI's recorded output. Both halves are hashed identically, so
 * a failure is a difference in the bytes produced rather than in how they were read back.
 *
 * The reference is regenerated by `scripts/generate-parity-fixture.mjs`, which runs the shipped
 * CLI. If the engine ever stops being deterministic the regenerate yields a different hash and
 * this fails loudly, rather than being quietly re-baselined to whatever the browser produced.
 */

// Playwright runs these specs as CommonJS — the root package.json sets no `"type": "module"`,
// and no other spec uses `import.meta` — so fixture paths resolve from the working directory and
// the reads cannot be top-level `await`.
const FIXTURE_DIR = join(process.cwd(), 'fixtures', 'parity');

type Fixture = { recipe: unknown; inputBytes: number[]; expectedHash: string };

let cached: Promise<Fixture> | undefined;
/** Read once and memoised, so a fixture failure names the file instead of surfacing as a hang. */
const loadFixture = (): Promise<Fixture> => {
  cached ??= (async () => ({
    recipe: JSON.parse(await readFile(join(FIXTURE_DIR, 'recipe.json'), 'utf8')),
    inputBytes: Array.from(
      await readFile(join(process.cwd(), 'fixtures', 'pdfs', 'one-page.pdf')),
    ),
    expectedHash: (await readFile(join(FIXTURE_DIR, 'cli-output.sha256'), 'utf8')).trim(),
  }))();
  return cached;
};

const hashOf = (bytes: number[] | Uint8Array): string =>
  createHash('sha256').update(Buffer.from(bytes)).digest('hex');

/**
 * Runs the recipe through the engine inside the page.
 *
 * Two constraints make this less obvious than an import, and both were found by failure:
 *
 * 1. `page.evaluate` bodies are not processed by Vite, so a bare specifier cannot resolve inside
 *    them. The engine is addressed through the workspace symlink under `node_modules`, which is
 *    inside Vite's serving allow list — `packages/engine/dist` is outside it, and requesting that
 *    path directly returns an HTML 403 that the browser caches as a module. The import then
 *    *appears* to succeed and fails later with a confusing error. `dist/` is also the exact
 *    artifact the CLI imports, so both halves run the same module.
 *
 * 2. The engine runs through `apps/web/src/lib/runRecipeForParity.ts`, a module the app itself
 *    imports, rather than through an `import()` inside `page.evaluate`. Both alternatives fail:
 *    a bare specifier cannot resolve in an evaluate body (it is not processed by Vite), and
 *    importing the engine by absolute path makes its
 *    `new URL('./inspect.worker.js', import.meta.url)` resolve against that path instead of the
 *    app's, so the worker never loads. Going through the app's module graph means Vite rewrites
 *    the worker URL correctly and `PdfViewer` has already set pdf.js's `workerSrc` on the very
 *    instance the engine resolves.
 *
 * Bytes come back as a plain number array rather than base64: a base64 hop decodes in the page
 * and re-encodes outside it, so a transport bug would be misattributed to the engine.
 */
const openHarness = async (page: import('@playwright/test').Page): Promise<void> => {
  await page.goto('/view-pdf');
  // The harness is installed by PdfViewer once its module graph has evaluated, so waiting for it
  // is what orders this correctly. Without the wait the evaluate below would race the import.
  await page.waitForFunction(() => '__runRecipeForParity' in globalThis, undefined, {
    timeout: 30_000,
  });
};

const runInPage = async (page: import('@playwright/test').Page): Promise<number[]> => {
  const { recipe, inputBytes } = await loadFixture();
  return page.evaluate(
    async (paths: { recipe: unknown; input: number[] }) => {
      const run = (globalThis as { __runRecipeForParity: (r: unknown, i: number[]) => Promise<number[]> })
        .__runRecipeForParity;
      return run(paths.recipe, paths.input);
    },
    { recipe, input: inputBytes },
  );
};

// Both tests get an explicit timeout: the recipe is run inside a real page twice, and under the
// full suite's parallelism the second run's evaluate can exceed the 30s default. The work is
// small — a two-step recipe over a one-page PDF — so a run that takes 30s is contention, not
// slowness, and timing out on that would make this a flake rather than a gate.
const PARITY_TIMEOUT_MS = 90_000;

test('a recipe produces byte-equivalent output in the browser and in Node', async ({ page }) => {
  const { expectedHash } = await loadFixture();
  // The recorded reference must be a real sha256. Without this the comparison below would pass
  // vacuously if the fixture file were emptied or turned into a path.
  assert.match(expectedHash, /^[0-9a-f]{64}$/u, 'cli-output.sha256 must hold a sha256');

  const pageErrors: string[] = [];
  page.on('pageerror', (error) => pageErrors.push(error.message));

  await openHarness(page);
  const browserBytes = await runInPage(page);
  const actual = hashOf(browserBytes);

  expect(
    pageErrors,
    'the page raised an uncaught error while running the recipe',
  ).toEqual([]);
  expect(
    actual,
    `browser ${actual} (${browserBytes.length} bytes) does not match the CLI's ${expectedHash}. ` +
      'The same recipe no longer produces the same bytes in both environments.',
  ).toBe(expectedHash);
});

test('the same recipe is byte-stable across two runs in the same page', async ({ page }) => {
  // The half the Node-only test could not see. A run must not stamp a wall-clock timestamp:
  // this is exactly the pdf-lib `updateMetadata` defect, which cost the CLI parity test an
  // intermittent failure for as long as it went unfixed.
  await openHarness(page);
  const first = await runInPage(page);
  // Long enough to cross a whole second, which is the resolution of the `/ModDate` that was
  // being stamped. Without the gap the test would pass even if fully broken.
  await page.waitForTimeout(1100);
  const second = await runInPage(page);

  expect(hashOf(second), 'the browser run is not byte-stable across a one-second gap').toBe(
    hashOf(first),
  );
}, PARITY_TIMEOUT_MS);