<script lang="ts">
  import Route from '../../pdf-to-csv/+page.svelte';
</script>

<!--
  Generated by scripts/generate-locale-routes.mjs — do not hand-edit.

  Renders the canonical route unchanged. The locale comes from the [locale]
  layout's context, which the page shells read, so a route is defined once and
  localized without a second copy of its props drifting out of date.
-->
<Route />
