<script lang="ts">
  import ConversionTool from '$lib/ConversionTool.svelte';
</script>

<!--
  Generated by scripts/generate-conversion-routes.mjs — do not hand-edit.

  One directional page per format × direction (README §24). The engine operation
  is shared with the opposite direction; only the entry point differs, which is
  why these are distinct pages rather than tabs on one.
-->
<ConversionTool
  title="PDF to PowerPoint (PPTX)"
  description="Turn PDF pages into PowerPoint (PPTX) locally, in your browser. Nothing is uploaded."
  format="pptx"
  direction="from-pdf"
  accept=".pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation"
/>
