<!--
  Generated by scripts/generate-tool-directory.mjs — do not hand-edit.

  Appendix E rule 9: every page links into the tool graph. 123 routes across 10 groups, derived from
  docs/route-manifest.json so the directory cannot drift from what ships.

  Rendered in the footer rather than the header: a 126-item header is not
  navigation, it is a wall, and on every tool page it would push the actual
  tool above the fold.
-->
<nav class="tool-directory" aria-labelledby="directory-heading">
  <h2 id="directory-heading">Every tool</h2>
  <section class="directory-group">
    <h2>Organize pages</h2>
    <ul>
      <li><a href="/bates-numbering">Bates numbering</a></li>
      <li><a href="/crop-pdf">Crop pages</a></li>
      <li><a href="/extract-pages">Extract pages</a></li>
      <li><a href="/halve-pages">Halve pages</a></li>
      <li><a href="/insert-pages">Insert pages</a></li>
      <li><a href="/merge">Merge PDFs</a></li>
      <li><a href="/organize">Organize pages</a></li>
      <li><a href="/pages-per-sheet">Pages per sheet</a></li>
      <li><a href="/remove-pages">Remove pages</a></li>
      <li><a href="/resize-pdf-pages">Change page size</a></li>
      <li><a href="/rotate-pdf">Rotate pages</a></li>
      <li><a href="/split">Split PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Convert to and from PDF</h2>
    <ul>
      <li><a href="/bmp-to-pdf">BMP image to PDF</a></li>
      <li><a href="/cbz-to-pdf">Comic book archive to PDF</a></li>
      <li><a href="/csv-to-pdf">Comma-separated values to PDF</a></li>
      <li><a href="/docx-to-pdf">Word (DOCX) to PDF</a></li>
      <li><a href="/epub-to-pdf">EPUB to PDF</a></li>
      <li><a href="/gif-to-pdf">GIF image to PDF</a></li>
      <li><a href="/heic-to-pdf">HEIC/HEIF image to PDF</a></li>
      <li><a href="/html-to-pdf">Pasted HTML to PDF</a></li>
      <li><a href="/jpg-to-pdf">JPEG image to PDF</a></li>
      <li><a href="/markdown-to-pdf">Markdown to PDF</a></li>
      <li><a href="/odg-to-pdf">OpenDocument Graphics to PDF</a></li>
      <li><a href="/odp-to-pdf">OpenDocument Presentation to PDF</a></li>
      <li><a href="/ods-to-pdf">OpenDocument Spreadsheet to PDF</a></li>
      <li><a href="/odt-to-pdf">OpenDocument Text to PDF</a></li>
      <li><a href="/pdf-to-cbz">PDF to Comic book archive</a></li>
      <li><a href="/pdf-to-csv">PDF to Comma-separated values</a></li>
      <li><a href="/pdf-to-docx">PDF to Word (DOCX)</a></li>
      <li><a href="/pdf-to-epub">PDF to EPUB</a></li>
      <li><a href="/pdf-to-html">PDF to Pasted HTML</a></li>
      <li><a href="/pdf-to-jpg">PDF to JPEG image</a></li>
      <li><a href="/pdf-to-markdown">PDF to Markdown</a></li>
      <li><a href="/pdf-to-odg">PDF to OpenDocument Graphics</a></li>
      <li><a href="/pdf-to-odp">PDF to OpenDocument Presentation</a></li>
      <li><a href="/pdf-to-ods">PDF to OpenDocument Spreadsheet</a></li>
      <li><a href="/pdf-to-odt">PDF to OpenDocument Text</a></li>
      <li><a href="/pdf-to-pdf-epub">PDF to EPUB extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-html">PDF to HTML extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-image">PDF to Rendered PDF pages</a></li>
      <li><a href="/pdf-to-pdf-markdown">PDF to Markdown extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-odp">PDF to ODP extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-ods">PDF to ODS extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-odt">PDF to ODT extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-rtf">PDF to RTF extracted from PDF</a></li>
      <li><a href="/pdf-to-pdf-txt">PDF to Text extracted from PDF</a></li>
      <li><a href="/pdf-to-png">PDF to PNG image</a></li>
      <li><a href="/pdf-to-pptx">PDF to PowerPoint (PPTX)</a></li>
      <li><a href="/pdf-to-rtf">PDF to Rich Text Format</a></li>
      <li><a href="/pdf-to-txt">PDF to Plain text</a></li>
      <li><a href="/pdf-to-xlsx">PDF to Excel (XLSX)</a></li>
      <li><a href="/pdf-to-zip">PDF to ZIP of pages or images</a></li>
      <li><a href="/png-to-pdf">PNG image to PDF</a></li>
      <li><a href="/pptx-to-pdf">PowerPoint (PPTX) to PDF</a></li>
      <li><a href="/psd-to-pdf">Photoshop (PSD) to PDF</a></li>
      <li><a href="/rtf-to-pdf">Rich Text Format to PDF</a></li>
      <li><a href="/svg-to-pdf">SVG image to PDF</a></li>
      <li><a href="/txt-to-pdf">Plain text to PDF</a></li>
      <li><a href="/webp-to-pdf">WebP image to PDF</a></li>
      <li><a href="/xlsx-to-pdf">Excel (XLSX) to PDF</a></li>
      <li><a href="/xml-einvoice-to-pdf">XML e-invoice to PDF</a></li>
      <li><a href="/zip-to-pdf">ZIP of pages or images to PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Other formats</h2>
    <ul>
      <li><a href="/bank-statement-to-excel">Bank statement → Excel</a></li>
      <li><a href="/csv-pdf">CSV ⇄ PDF</a></li>
      <li><a href="/design-file-to-pdf">Design files → PDF</a></li>
      <li><a href="/epub-pdf">EPUB ⇄ PDF</a></li>
      <li><a href="/excel-pdf">Excel ⇄ PDF</a></li>
      <li><a href="/html-pdf">HTML ⇄ PDF</a></li>
      <li><a href="/image-to-pdf">Images → PDF</a></li>
      <li><a href="/odf-pdf">OpenDocument ⇄ PDF</a></li>
      <li><a href="/other-formats-to-pdf">Legacy formats → PDF</a></li>
      <li><a href="/ppt-pdf">PowerPoint ⇄ PDF</a></li>
      <li><a href="/text-pdf">Text, RTF and Markdown ⇄ PDF</a></li>
      <li><a href="/word-pdf">Word ⇄ PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Optimize and repair</h2>
    <ul>
      <li><a href="/compress-pdf">Compress PDF</a></li>
      <li><a href="/flatten-pdf">Flatten PDF</a></li>
      <li><a href="/optimize-for-web">Optimize for web</a></li>
      <li><a href="/repair-pdf">Repair PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Export</h2>
    <ul>
      <li><a href="/bookmarks">Bookmarks</a></li>
      <li><a href="/extract-images">Extract embedded images</a></li>
      <li><a href="/ocr-pdf">OCR a PDF</a></li>
      <li><a href="/pdf-to-image">PDF → images</a></li>
      <li><a href="/pdf-to-pdfa">PDF/A conformance</a></li>
      <li><a href="/rasterize-pdf">Rasterize PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Edit and inspect</h2>
    <ul>
      <li><a href="/add-image">Add an image</a></li>
      <li><a href="/add-text">Add text</a></li>
      <li><a href="/annotate">Annotate</a></li>
      <li><a href="/compare-pdf">Compare PDFs</a></li>
      <li><a href="/create-form">Create a form</a></li>
      <li><a href="/editor">PDF editor</a></li>
      <li><a href="/fill-form">Fill a form</a></li>
      <li><a href="/headers-footers">Headers and footers</a></li>
      <li><a href="/page-numbers">Page numbers</a></li>
      <li><a href="/pdf-inspector">Inspect structure</a></li>
      <li><a href="/pdf-metadata">Edit metadata</a></li>
      <li><a href="/pdf-overlay">Overlay a PDF</a></li>
      <li><a href="/view-pdf">View a PDF</a></li>
      <li><a href="/watermark-pdf">Watermark</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Sign, protect, redact</h2>
    <ul>
      <li><a href="/password-generator">Password generator</a></li>
      <li><a href="/pdf-accessibility">Accessibility tagging</a></li>
      <li><a href="/protect-pdf">Protect a PDF</a></li>
      <li><a href="/redact-pdf">Redact a PDF</a></li>
      <li><a href="/remove-signature-background">Remove a signature background</a></li>
      <li><a href="/request-signature">Request signatures</a></li>
      <li><a href="/sign-pdf">Sign a PDF</a></li>
      <li><a href="/unlock-pdf">Unlock a PDF</a></li>
      <li><a href="/verify-signature">Verify a signature</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Create</h2>
    <ul>
      <li><a href="/create-pdf">Create a PDF</a></li>
      <li><a href="/document-pack-builder">Document pack</a></li>
      <li><a href="/e-invoice">Electronic invoice</a></li>
      <li><a href="/invoice-creator">Invoice creator</a></li>
      <li><a href="/qr-code">QR code</a></li>
      <li><a href="/scan-to-pdf">Scan to PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>Workflows</h2>
    <ul>
      <li><a href="/batch">Batch runner</a></li>
      <li><a href="/recipe">Recipe builder</a></li>
      <li><a href="/watch">Folder watcher</a></li>
      <li><a href="/webpage-to-pdf">Webpage → PDF</a></li>
    </ul>
  </section>
  <section class="directory-group">
    <h2>AI (optional, BYOK)</h2>
    <ul>
      <li><a href="/ai-to-pdf">Illustrator (AI) to PDF</a></li>
      <li><a href="/ai/chat-with-pdf">Chat with a PDF</a></li>
      <li><a href="/ai/escalations">AI escalation routes</a></li>
      <li><a href="/ai/generate-pdf">Generate a PDF</a></li>
      <li><a href="/ai/summarize">Summarize a PDF</a></li>
      <li><a href="/ai/translate">Translate a PDF</a></li>
    </ul>
  </section>
</nav>

<style>
  .tool-directory {
    display: grid;
    gap: 32px;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    margin: 0 auto;
    max-width: 1280px;
    padding: 48px 40px;
  }
  .tool-directory > h2 {
    font-size: 1.25rem;
    grid-column: 1 / -1;
    letter-spacing: -0.02em;
    margin: 0;
  }
  h2 {
    color: var(--color-muted);
    font-size: 0.875rem;
    font-weight: 600;
    letter-spacing: 0.08em;
    margin: 0 0 12px;
    text-transform: uppercase;
  }
  ul {
    display: flex;
    flex-direction: column;
    gap: 6px;
    list-style: none;
    margin: 0;
    padding: 0;
  }
  a {
    color: inherit;
    font-size: 0.9375rem;
    text-decoration: none;
  }
  a:hover,
  a:focus-visible {
    text-decoration: underline;
  }
  @media (max-width: 767px) {
    .tool-directory {
      padding-inline: 24px;
    }
  }
</style>
